version: '3.8'

services:

  db:
    container_name: db-container-react-java-mysql-OmerPeled
    restart: always
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db-57xsl
      MYSQL_DATABASE: example
      MYSQL_HOST: db
      MYSQL_PASSWORD: db-57xsl
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - react0mysql

  backend:
    container_name: backend-container-react-java-mysql-OmerPeled
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: db-57xsl
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/example
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: db-57xsl

    volumes:
      - ./backend/src/main/resources/application.properties:/backend/src/main/resources/application.properties
    networks:
      - react0mysql

  frontend:
    container_name: frontend-container-react-java-mysql-OmerPeled
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - react0mysql

networks:
  react0mysql:
    driver: bridge

volumes:
  db_data: