name: Build, Test, and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Images
      run: docker compose build

    - name: Start Containers
      run: docker compose up -d
      # Start all services in detached mode

    - name: Wait for services to stabilize
      run: |
        sleep 30  # Allow some time for services to stabilize

    - name: Check backend container logs
      run: |
        docker logs backend-container-react-java-mysql-OmerPeled

    - name: Verify containers are running
      run: |
        docker ps -a
      continue-on-error: true

    - name: Test DB Container
      run: |
        docker exec db-container-react-java-mysql-OmerPeled mysql -uroot -pdb-57xsl -e "SHOW DATABASES;"
      continue-on-error: true

    - name: Test Backend Container
      run: |
        curl -f http://127.0.0.1:8080

    - name: Test Frontend Container
      run: |
        curl -f http://127.0.0.1:3000

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws/j8p9i7s1/omerpeled-finalexam-module3
    
    - name: Tag backend image
      run: |
        IMAGE_TAG=latest
        ECR_URI=public.ecr.aws/j8p9i7s1/omerpeled-finalexam-module3
        docker tag backend-container-react-java-mysql-OmerPeled:latest $ECR_URI:backend-$IMAGE_TAG

    - name: Push backend image to ECR Public
      run: |
        IMAGE_TAG=latest
        ECR_URI=public.ecr.aws/j8p9i7s1/omerpeled-finalexam-module3
        docker push $ECR_URI:backend-$IMAGE_TAG

    - name: Tag frontend image
      run: |
        IMAGE_TAG=latest
        ECR_URI=public.ecr.aws/j8p9i7s1/omerpeled-finalexam-module3
        docker tag frontend-container-react-java-mysql-OmerPeled:latest $ECR_URI:frontend-$IMAGE_TAG

    - name: Push frontend image to ECR Public
      run: |
        IMAGE_TAG=latest
        ECR_URI=public.ecr.aws/j8p9i7s1/omerpeled-finalexam-module3
        docker push $ECR_URI:frontend-$IMAGE_TAG

    - name: Clean up
      run: docker compose down
      if: always()
