name: Build, Test, and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Images
      run: docker-compose build

    - name: Start Containers
      run: docker-compose up -d
      # Start all services in detached mode

    - name: Test DB Container
      run: |
        sleep 30 # wait for the DB to initialize
        docker exec db-container-react-java-mysql-OmerPeled mysql -uroot -pdb-57xsl -e "SHOW DATABASES;"
      continue-on-error: true

    - name: Test Backend Container
      run: |
        sleep 30 # wait for the backend to initialize
        curl -f http://localhost:8080/actuator/health

    - name: Test Frontend Container
      run: |
        sleep 30 # wait for the frontend to initialize
        curl -f http://localhost:3000

    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: ${{ secrets.NEXUS_REGISTRY }}
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}
        format: docker
        repository: docker-repo
        coordinates: groupId=com.example artifactId=app version=1.0.0
        assets: extension=jar
        filename: ./target/app-1.0.0.jar

    - name: Clean up
      run: docker-compose down
      if: always()
